### ISSUE TITLE
Documentation clarification

### ISSUE THREAD

**Issue by jamesnvc** [keyboardio/Kaleidoscope-LED-Stalker#9]
- [x] In the sample code, why does this plugin use `USE_PLUGINS`, while the others use `Kaleidoscope.use`?
- [ ] It would be useful to have some reference to how one declares colours - under `Haunt` it states that it takes a colour as a parameter and we see the CRGB macro in the example, but are the other ways to make colours?

**Comment by algernon** [comment]
`USE_PLUGINS` was the way to tell Kaleidoscope to use a plugin, until recently. The documentation of plugins I touched since the change has been updated, the others weren't, yet. In due time, all of them will be updated to use `Kaleidoscope.use`. Good catch!

As for colors: there are other ways, but using the `CRGB` macro is the most straightforward, and the most portable across keyboards. I wouldn't want to mention the other options, that would be too confusing for a novice, I think. In the rare case where one would want to use any of the other options, they can do so by a cursory look at the source code.

My aim with the documentation is to document the recommended ways, the things one should know to get started. It is not a complete API documentation.

Does that make sense?
